name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !startsWith(github.event.head_commit.message, 'ci:') &&
      !contains(github.event.head_commit.message, '[skip_ci]')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - name: Install nox
      run: pip install nox==2020.12.31
    - name: Install poetry
      run: pip install poetry==1.1.4
    - name: Checkout submodules
      run: git submodule update --init --recursive --depth=1
    - name: Run pytest, coverage and upload results to codecov
      run: nox --sessions tests-3.9 codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
