name: Create Repository Labels

on:
  push:
    branches:
      - main
      - master
      - devel
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml
  pull_request:
    branches:
      - main
      - master
      - devel
    paths:
      - .github/labels.yaml
      - .github/workflows/labeler.yml
  schedule:
    - cron: "0 0 * * TUE"

jobs:
  labels:
    name: Sycnchronize repository labels
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.0

      - name: Sync GitHub Issue Labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.MCKIT_GITHUB_TOKEN }}
          skip-delete: true
          dry-run: ${{ github.event_name != 'pull_request' }}
          exclude: |
            help*
            *issue
