name: MCKit Tests

on:
  push:
    branches:
      - "master"
      - "devel"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yml"
  pull_request:
    branches:
      - "master"
      - "devel"
#    workflow_dispatch:
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yml"
jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    if: |
      !startsWith(github.event.head_commit.message, 'bump:') &&
      !contains(github.event.head_commit.message, '[skip_ci]')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
        exclude:
          - os: windows-latest
            python-version: 3.7   # py37 on Windows takes too much efforts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1
      - name: Install nox
        run: pip install nox==2021.6.12
      - name: Install poetry
        run: pip install poetry==1.1.8
      - name: Run Safety test
        run: nox -s safety
        if: matrix.python-version == '3.9'  && matrix.os == 'ubuntu-latest'
      - name: Run nox tests
        run: nox -s tests -p ${{ matrix.python-version }}
