name: Tests

on:
  push:
    branches:
      - "master"
      - "devel"
      - "main"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "**/data/**"
      - ".github/constraints.txt"
      - "!adhoc/**"
      - "!tools/**"
  pull_request:
    branches:
      - "master"
      - "devel"
      - "main"
    paths:
      - "**.py"
      - "**.c"
      - "**.h"
      - "**.yaml"
      - "**.yml"
      - "**.toml"
      - "!adhoc/**"
      - "!tools/**"


concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:

  lint:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip_ci]')
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Install Nox
        run: |
          pip install --constraint=.github/constraints.txt nox
          nox --version

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3.2.5
        with:
          path: |
            .cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry config --local cache-dir .cache/pypoetry
          poetry config --local virtualenvs.create false

      - name: Run safety session
        run: |
          nox --force-color --session=safety

      - name: Run pre commit checks
        run: |
          nox --force-color --session=pre-commit

#      - name: Run mypy static type checks
#        run: |
#          nox --force-color --session=mypy

  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth=1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Install Nox
        run: |
          pip install --constraint=.github/constraints.txt nox
          nox --version

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3.2.5
        with:
          path: |
            .cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry config --local cache-dir .cache/pypoetry
          poetry config --local virtualenvs.create false
          poetry env info

      - name: Build documentation
        run: |
          nox --force-color --session=docs-build

  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive --depth=1

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip virtualenv
          pip --version

      - name: Install nox
        run: |
          pip install --constraint=.github/constraints.txt nox
          nox --version

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3.2.5
        with:
          path: |
            .cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry config --local cache-dir .cache/pypoetry
          poetry config --local virtualenvs.create false
          poetry env info

      - name: Run nox tests
        run: nox  --force-color --session tests --python ${{ matrix.python-version }}

      - name: Upload coverage data
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-data
          path: ".coverage.*"

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:

      - name: Check out the repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'

      - name: Use frozen pip version
        run: |
          pip install --constraint=.github/constraints.txt pip
          pip --version

      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v3.2.5
        with:
          path: |
            .cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          pip install --constraint=.github/constraints.txt poetry
          poetry --version
          poetry config --local cache-dir .cache/pypoetry
          poetry config --local virtualenvs.create false
          poetry env info

      - name: Install Nox
        run: |
          pip install --constraint=.github/constraints.txt nox
          nox --version

      - name: Download coverage data
        uses: actions/download-artifact@v3.0.2
        with:
          name: coverage-data

      - name: Combine coverage data and display human readable report
        run: |
          nox --force-color --session=coverage

      - name: Create coverage report
        run: |
          nox --force-color --session=coverage -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.1
